
jobs:
- job: 'Build'
  pool:
    vmImage: 'Ubuntu 18.04'
  variables:
    PYTHON: 3.7.3
    BUILD_DOCS: 1

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Linux - Add conda to PATH'
    condition: eq(variables['agent.os'], 'Linux' )

  # Linux
  - bash: |
      # Fix Anaconda permissions
      sudo install -d -m 0777 /usr/share/miniconda/
      sudo install -d -m 0777 /usr/share/miniconda/envs
    displayName: 'Linux - Prepare OS'
    condition: eq(variables['agent.os'], 'Linux' )

  - bash: |
      conda config --set always_yes yes
      conda config --set channel_priority strict
      conda config --set show_channel_urls yes
      conda config --add channels conda-forge
    displayName: 'Anaconda - Configure'

  - bash: |
     conda create --name build-environment python=$(PYTHON) conda-build anaconda-client
    displayName: 'Anaconda - Create'

  - bash: |
      source activate build-environment
      conda build conda-recipe --output-folder bld-dir
    displayName: 'Anaconda - Build PyDM Package'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish - Anaconda Package'
    inputs:
      PathtoPublish: 'bld-dir'
      ArtifactName: 'anaconda_package'

  - bash: |
      conda config --add channels 'file:///$(Build.Repository.LocalPath)/bld-dir'
      source activate build-environment
      conda install pydm
    displayName: 'Anaconda - Configure - Add local bld-dir'

  - bash: |
      source activate build-environment
      pip install -r docs-requirements.txt
      pushd docs
      make html
      popd
    displayName: 'Documentation - Build HTML'
    condition: |
      and(
        and(
          eq(variables['agent.os'], 'Linux' ),
          eq(variables['BUILD_DOCS'], 1)
        ),
        succeeded()
      )

  - task: PublishBuildArtifacts@1
    displayName: 'Publish - Documentation'
    inputs:
      PathtoPublish: 'docs/build/html/'
      ArtifactName: 'docs_html'
    condition: |
      and(
        and(
          eq(variables['agent.os'], 'Linux' ),
          eq(variables['BUILD_DOCS'], 1)
        ),
        succeeded()
      )
