{% set data = load_setup_py_data() %}

package:
    name    : pydm
    version : {{ data.get('version') }}

source:
    path: ..

build:
  noarch: python

requirements:
    build:
      - python
      - pip
      - setuptools
      - pyqt >=5
      - qtpy

    run:
      - python
      - six
      - numpy >=1.11.0
      - scipy >=0.12.0
      - pyepics >=3.2.7
      - requests >=1.1.0
      - psutil
      - pyqt >=5
      - pyqtgraph
      - qtpy

test:
    imports:
      - pydm

about:
  home: https://github.com/slaclab/pydm
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md
  summary: 'Python Display Manager'

  description: |
    PyDM is a PyQt-based framework for building user interfaces for control systems.
    The goal is to provide a no-code, drag-and-drop system to make simple screens,
    as well as a straightforward Python framework to build complex applications.
  doc_url: https://slaclab.github.io/pydm/
  dev_url: https://github.com/slaclab/pydm
